---
abstract: 'A programmatic way to access Gentoo.org Mirror Metadata'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
generated_by: 'Dist::Zilla version 1.092930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gentoo-MirrorList
provides:
  Gentoo::MirrorList:
    file: lib/Gentoo/MirrorList.pm
    version: 0.01000102
  Gentoo::MirrorList::Mirror:
    file: lib/Gentoo/MirrorList/Mirror.pm
    version: 0.01000102
requires:
  App::Cache: 0.36
  Moose: 0.92
  XML::Simple: 2.18
  namespace::autoclean: 0.09
resources:
  repository: http://github.com/kentfredric/Gentoo-MirrorList
version: 0.01000102
